#!/usr/bin/env python3
"""Rebuild the stampd logo vectors from docs/logo-source.png.

    brew install potrace imagemagick
    python3 scripts/logo/build-logo.py

Emits, into apps/dashboard/:
  public/stampd-{mark,lockup}-{light,dark}.svg   standalone, explicit colours
  src/components/LogoArt.tsx                     inline React, ink = currentColor

The source is white line art on transparency. Rather than trace it as-is, the alpha
channel is used as the mask so the ink colour is decided at render time, and the blue
check is split into its own layer first so it survives as a separate fill.
"""

import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from pngio import load  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "docs/logo-source.png"
PUBLIC = ROOT / "apps/dashboard/public"
COMPONENT = ROOT / "apps/dashboard/src/components/LogoArt.tsx"
WORK = ROOT / ".logo-build"

# Content bounds measured from the source; the surrounding canvas is empty.
REGIONS = {"mark": (575, 203, 967, 571), "lockup": (508, 203, 1024, 746)}

# Padding keeps mkbitmap's 2x upscale from pushing strokes past the crop edge, which
# otherwise clips the outer glyphs of the wordmark.
PAD = 12

THEMES = {"light": ("#1c1b19", "#3f72c4"), "dark": ("#f0ede7", "#96b4e6")}

BLUE_DELTA = 18  # B - R above this marks the check-mark layer


def write_pgm(path, rows, w, h, box, want_blue):
    x0, y0, x1, y1 = box
    x0 = max(0, x0 - PAD)
    y0 = max(0, y0 - PAD)
    x1 = min(w - 1, x1 + PAD)
    y1 = min(h - 1, y1 + PAD)
    out = bytearray()
    for y in range(y0, y1 + 1):
        r = rows[y]
        for x in range(x0, x1 + 1):
            o = x * 4
            red, _, blue, alpha = r[o], r[o + 1], r[o + 2], r[o + 3]
            is_blue = blue > red + BLUE_DELTA and alpha > 100
            # potrace reads black as ink, so opaque becomes 0.
            out.append(255 - (alpha if is_blue == want_blue else 0))
    path.write_bytes(b"P5\n%d %d\n255\n" % (x1 - x0 + 1, y1 - y0 + 1) + bytes(out))


def trace(pgm, svg):
    pbm = pgm.with_suffix(".pbm")
    subprocess.run(["mkbitmap", "-f", "4", "-s", "2", "-t", "0.45", "-o", str(pbm), str(pgm)], check=True)
    subprocess.run(["potrace", "-s", "-a", "1.2", "-O", "0.3", "-t", "4", "-o", str(svg), str(pbm)], check=True)


def parse(svg):
    s = svg.read_text()
    viewbox = " ".join(str(int(float(n))) for n in re.search(r'viewBox="([^"]+)"', s).group(1).split())
    group = re.search(r'<g transform="([^"]+)"[^>]*>(.*?)</g>', s, re.S)
    paths = "".join(f'<path d="{d}"/>' for d in re.findall(r'<path d="([^"]+)"', group.group(2)))
    return viewbox, group.group(1), paths


def main():
    if not SRC.exists():
        sys.exit(f"missing {SRC}")
    WORK.mkdir(exist_ok=True)
    w, h, rows = load(str(SRC))

    parts = {}
    for tag, box in REGIONS.items():
        layers = {}
        for layer, want_blue in (("ink", False), ("chk", True)):
            pgm = WORK / f"{tag}-{layer}.pgm"
            svg = WORK / f"{tag}-{layer}.svg"
            write_pgm(pgm, rows, w, h, box, want_blue)
            trace(pgm, svg)
            layers[layer] = parse(svg)
        (viewbox, ink_tr, ink_d) = layers["ink"]
        (_, chk_tr, chk_d) = layers["chk"]
        parts[tag] = (viewbox, ink_tr, ink_d, chk_tr, chk_d)

        for theme, (ink_c, chk_c) in THEMES.items():
            out = (
                f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" role="img" aria-label="stampd">'
                f'<g transform="{ink_tr}" fill="{ink_c}" stroke="none">{ink_d}</g>'
                f'<g transform="{chk_tr}" fill="{chk_c}" stroke="none">{chk_d}</g></svg>\n'
            )
            (PUBLIC / f"stampd-{tag}-{theme}.svg").write_text(out)
            print(f"public/stampd-{tag}-{theme}.svg  {len(out)} bytes")

    def component(name, tag):
        viewbox, ink_tr, ink_d, chk_tr, chk_d = parts[tag]
        return f"""export function {name}({{title, ...props}}: SvgProps) {{
    return (
        <svg
            viewBox="{viewbox}"
            xmlns="http://www.w3.org/2000/svg"
            role={{title ? "img" : "presentation"}}
            aria-label={{title}}
            aria-hidden={{title ? undefined : true}}
            focusable="false"
            {{...props}}
        >
            <g transform="{ink_tr}" fill="currentColor" stroke="none">{ink_d}</g>
            <g transform="{chk_tr}" fill="var(--logo-check)" stroke="none">{chk_d}</g>
        </svg>
    );
}}
"""

    header = (
        "// Generated by scripts/logo/build-logo.py from docs/logo-source.png. Do not edit.\n"
        "//\n"
        "// Ink is `currentColor`, so one component covers both themes: the mark inherits\n"
        "// whatever colour the surrounding text has. The check keeps its hue via --logo-check.\n"
        'import type {SVGProps} from "react";\n\n'
        "type SvgProps = SVGProps<SVGSVGElement> & {title?: string};\n\n"
    )
    COMPONENT.write_text(header + component("StampdMark", "mark") + "\n" + component("StampdLockup", "lockup"))
    print(f"src/components/LogoArt.tsx  {COMPONENT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
